### ISSUE TITLE
Add structure to your application

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/Football-statistic-app#1]
Add header and centered content.

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
Header and container should be visible. Like you previously did in FirstJSApp:

![image](https://user-images.githubusercontent.com/11459051/32102878-d73ec8ec-bb26-11e7-9e77-7f7a89493126.png)

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
Move links to the header.
Add "TODO: content will be here" text in the container.
