### ISSUE TITLE
Active link is not highlighted

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/Football-statistic-app#10]
Steps to reproduce:

1.Go to Teams
2. Teams link is highlighted
3. Refresh page (F5)

**Expected behavior:**
Teams link is highlighted

**Current behavior:**
Teams link is not highlighted

![image](https://user-images.githubusercontent.com/11459051/32334701-d191e650-bff3-11e7-8aea-ae650f51c884.png)

**Comment by IvanKhud** [comment]
done
