### ISSUE TITLE
Rework search

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/Football-statistic-app#11]
Example for `Championships`

This is the initial state of `championships` page:
![image](https://user-images.githubusercontent.com/11459051/32335090-baa6dfe4-bff4-11e7-9962-38d4c5a09f37.png)

After click on 'championships' text - page should look like this:
![image](https://user-images.githubusercontent.com/11459051/32335098-bfd1736c-bff4-11e7-93e2-69c72fba044a.png)

Do the same for `Teams` and `Matches`

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
To snow that there is the ability to search - show cursor as the pointer when it hovers over search icon and header name.

**Comment by IvanKhud** [comment]
done
