### ISSUE TITLE
Fetch API data once

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/Football-statistic-app#12]
The application sends a new request every time when you navigate between pages.

Example:
Navigate in this order

```
championships
teams
championships
matches
```

In this case, you should send request for championships once
But now it is sending request twice:
![image](https://user-images.githubusercontent.com/11459051/32335194-fb1465e2-bff4-11e7-9fa2-1fa32853f958.png)

Try to cache results.

**Comment by IvanKhud** [comment]
done
