### ISSUE TITLE
Add loading spinner while app waiting for response

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/Football-statistic-app#13]
When the application is waiting for response user see:

![image](https://user-images.githubusercontent.com/11459051/32336166-3abb99ac-bff7-11e7-91d4-8889007b2eb5.png)

![image](https://user-images.githubusercontent.com/11459051/32336483-1c02d5ec-bff8-11e7-8b25-2fc87303d1c5.png)

Add loading spinner while response data is not ready:

![image](https://user-images.githubusercontent.com/11459051/32336689-9dfa9418-bff8-11e7-8f14-bf17ef1fa63a.png)

![image](https://user-images.githubusercontent.com/11459051/32336709-ac3d8332-bff8-11e7-9fbc-ef0f0aba3281.png)

Do the same for **Championships**.
See example of spinner here http://plnkr.co/edit/PUjrEIt0YLTwr0rUInv8?p=preview

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
Did you test it?
Is it working locally for you? 
I could not see spinner at all, even if I using 'slow 3G' option in chrome dev tools:
![image](https://user-images.githubusercontent.com/11459051/32405265-d5919fac-c16a-11e7-92d6-05d7e413e7e5.png)

**Comment by IvanKhud** [comment]
fixed

**Comment by i10111pn** [comment]
Add loading spinner for `Championships`.
And hide all content while spinner is visible (search input is visible):

![image](https://user-images.githubusercontent.com/11459051/32405808-ee79b522-c174-11e7-924f-6d9f1c25fbd6.png)

**Comment by IvanKhud** [comment]
done
