### ISSUE TITLE
Details are not shown

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/Football-statistic-app#14]
**Steps to reproduce (v1):**

Click on links
http://football-stat-app.herokuapp.com/index.html#!/championships/1
http://football-stat-app.herokuapp.com/index.html#!/teams/87
http://football-stat-app.herokuapp.com/index.html#!/matches/0

**Steps to reproduce (v2):**

1.Go to `Championships` or `Teams` or `Matches`
2. Click on any item
3. Details are shown
5. Press F5 button

**Expected behavior:**
Details are shown

**Current behavior:**
Details are not shown

![image](https://user-images.githubusercontent.com/11459051/32463807-8129bb92-c346-11e7-81fd-05e0e40ae646.png)

![image](https://user-images.githubusercontent.com/11459051/32463827-947c6f28-c346-11e7-861b-c2032f66d639.png)

![image](https://user-images.githubusercontent.com/11459051/32463845-a4b97a34-c346-11e7-92c8-0348593fcb24.png)

**Comment by IvanKhud** [comment]
fixed

**Comment by i10111pn** [comment]
When you are refreshing page it is not working for a match.
Also, in not working for a match by direct link:
http://football-stat-app.herokuapp.com/index.html#!/matches/0 

Also, `Teams` and `Matches` tables have wrong header name (both named Championships)

**Comment by IvanKhud** [comment]
fixed
