### ISSUE TITLE
Matches are not shown

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/Football-statistic-app#18]
**Steps to reproduce:**
1.Go to `Matches`
2. Press F5 button

**Expected behavior:**
Matches are shown

**Current behavior:**
Matches are not shown

Note, you have an error in console:
![image](https://user-images.githubusercontent.com/11459051/32572174-79ae3c5c-c4d2-11e7-9a7e-573dcc44bf75.png)

**Comment by IvanKhud** [comment]
fixed
