### ISSUE TITLE
Add eslint to your app

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/Football-statistic-app#19]
Add linter to your app.
Follow this instruction:

**1.** Run in cmd:
```
npm install --save-dev eslint
npm install -g eslint
```

**2.** Run in cmd: `eslint --init`
Answer in this order:
**Inspect your JavaScript file(s)**
Files path **js/*.js**
Format - **json**
**No** for ES6
Run in **Browser**
**No** for CommonJS
**No** for JSX

**3.** To check if eslint works run this command in cmd:
`eslint js/match.controller.js`

**4.** Run in cmd: `npm install --save-dev eslint-plugin-angular`

**5.** Use the shareable config by adding it to your .eslintrc:
`“extends”: “plugin:angular/johnpapa”`

**6.** Manually add plugins section:

```
{
    "plugins": [
        "angular"
    ],
    "rules": {
     …
}

```
**7.** Run in cmd: `npm install -g eslint-plugin-angular`

Now your config is ready, just run `eslint js/*.js`
Try to fix all gotten errors/warnings.

**Comment by plant99** [comment]
@i10111pn  @IvanKhud  I want to work on it.

**Comment by IvanKhud** [comment]
done
