### ISSUE TITLE
App enhancements

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/Football-statistic-app#20]
**1.** Set `header` height to 60px

**2.** Remove `logo` highlighting

![image](https://user-images.githubusercontent.com/11459051/32606340-a471f70e-c55d-11e7-9f0c-48aa21996bb4.png)

**3.** Align content to the left on `championship` page
Set properties names to bold

![image](https://user-images.githubusercontent.com/11459051/32606771-421c1920-c55f-11e7-956b-cd3105fa69e8.png)

**4.** Remove the second border from the left side of `championship` page:
![image](https://user-images.githubusercontent.com/11459051/32606644-bc0e0f96-c55e-11e7-93d4-9e0ceb17915b.png)

**5.** Align content to the left on `team` page

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
Header lost border and background color. Add them back.

**Comment by i10111pn** [comment]
Also, add left padding to the `championship`, `team`  and `about` pages.

http://football-stat-app.herokuapp.com/index.html#!/championships/1
http://football-stat-app.herokuapp.com/index.html#!/teams/87
http://football-stat-app.herokuapp.com/index.html#!/about

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
Make height of active menu item the same as height of the header

![image](https://user-images.githubusercontent.com/11459051/32619297-f7ba3802-c582-11e7-9b18-bf4cc25756c6.png)

If it will work for you - just decrease the height of the header.

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
Do the same when you hover over links:

![image](https://user-images.githubusercontent.com/11459051/32620822-2e282eea-c587-11e7-8d90-a0d65565a744.png)

**Comment by IvanKhud** [comment]
done
