### ISSUE TITLE
Format your code

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/Football-statistic-app#21]
**1.** Align properly all the code in all the files.

**2.** Change css selectors in `style.css` according to this naming conventions:
https://google.github.io/styleguide/htmlcssguide.html#ID_and_Class_Name_Delimiters

**3.** Reformat too long lines in html templates.

**4.** Add new line before all `for` loops in `data.factory.js`

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
Reformat too long lines in 
`matches.template.html`
`teams.template.html`

**Comment by IvanKhud** [comment]
done
