### ISSUE TITLE
Refactor data fetching

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/Football-statistic-app#22]
You fetching all the data at one time and uses it where you need.

Instead of this, try to fetch only that you need at some moment.
Use promises for this.

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
Go to `Matches`.
Open Console -> Network.
Filter network results by "foot" (1 - in the picture)
Refresh the page.
For `Matches`, you are fetching `/championships/`  (2 - in the picture)

![image](https://user-images.githubusercontent.com/11459051/32702999-22546980-c7f8-11e7-8d17-47aa8cda13e0.png)

**Comment by IvanKhud** [comment]
Yes, i need to load championships, because matches page include championship logo and link to championship.

**Comment by i10111pn** [comment]
Get logo from this API
`https://footballbet.com.ua/teams/country/file-name.png`
`file-name.png` you can get in `Matches` response, see `image` key

Example:
https://footballbet.com.ua/teams/country/champions-league.png
![image](https://user-images.githubusercontent.com/11459051/32703301-63798e5a-c7fc-11e7-9d17-70f8f5320216.png)

**Comment by i10111pn** [comment]
> and link to championship.

link to a championship is on `match` page, not `matches`

**Comment by IvanKhud** [comment]
done
