### ISSUE TITLE
Spinner position 

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/Football-statistic-app#23]
**Steps to reproduce:**
1. Open: Console (F12) -> Network
2. Set "Slow 3G"
![image](https://user-images.githubusercontent.com/11459051/32621902-08095696-c58a-11e7-9661-a6fca533226e.png)
3. Go to `Championships`, `Teams` or `Matches` and refresh the page

**Expected behavior:**
Spinner is centered

**Current behavior:**
Spinner aligned to the left

![image](https://user-images.githubusercontent.com/11459051/32622198-cf2533ee-c58a-11e7-91dc-bad62c3cd815.png)

**Comment by IvanKhud** [comment]
fixed
