### ISSUE TITLE
Header enhancement 

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/Football-statistic-app#5]
1. Add a logo to the header.
2. Remove "Football statistics application" text.
3. Remove link's borders.

The header should look like this:
![image](https://user-images.githubusercontent.com/11459051/32171195-fd8bf762-bd7f-11e7-9956-d08e9791f5fb.png)

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
Make the main container wider and align header content to the main container:
![image](https://user-images.githubusercontent.com/11459051/32274441-7fc7ae2a-bf0f-11e7-830b-8a6963725234.png)

**Comment by IvanKhud** [comment]
done
