### ISSUE TITLE
Add pagination

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/Football-statistic-app#6]
Add pagination to the list of

```
Championships
Teams
Matches
```

if a list contains more than 10 items.

Use this for pagination
https://angular-ui.github.io/bootstrap/ (scroll to 'Pagination (ui.bootstrap.pagination)')

**Comment by IvanKhud** [comment]
done

**Comment by i10111pn** [comment]
Could not see this at Heroku.

**Comment by IvanKhud** [comment]
could you check heroku now?
