### ISSUE TITLE
Add details

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/Football-statistic-app#7]
Show details of

```
Championships
Teams
Matches
```

by clicking on a list's item.

**Championship details:**
![image](https://user-images.githubusercontent.com/11459051/32171364-8bb4fd5e-bd80-11e7-8b55-b3840f5f499d.png)

**Team details:**
![image](https://user-images.githubusercontent.com/11459051/32171381-9557f9d8-bd80-11e7-90a8-dda8864dc7f3.png)

**Matches details:**
![image](https://user-images.githubusercontent.com/11459051/32172590-cdf5ebca-bd84-11e7-9511-5b74d72327d6.png)

**Comment by IvanKhud** [comment]
done, but there is a bug - after reloading details page is empty. Working to fix this
