### ISSUE TITLE
Empty pagination's result page

### ISSUE THREAD

**Issue by i10111pn** [IvanKhud/Football-statistic-app#9]
**Steps to reproduce:**
1. Go to Teams
2. Enter Ди In search input
3. Сlick on page 2
**Expected behavior:**
Some results are showed

**Current behavior:**
Page is empty

![image](https://user-images.githubusercontent.com/11459051/32333969-e002b086-bff1-11e7-8b81-f0f2af3809e9.png)

**Comment by IvanKhud** [comment]
fixed
